name: Build & Upload
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Update Submodules
        run: ./gradlew updateSubmodules
      - name: Apply Patches
        run: ./gradlew applyPatches
      - name: Build
        run: |
          cd target/
          mvn clean package
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.3.3
        with:
          path: target/target/*.jar
